### ISSUE TITLE
Should the server wait for a response from the client when communicating via UDP?

### ISSUE THREAD

**Issue by oiooio** [TINF15ITNS/MB#1]
Especially when the consumer deregisters from the server. Is it necessary to wait for some kind of acknowledgement by the server?

(Taken from the readme)

**Comment by naibaf0** [comment]
It was my understanding that we would use UDP exclusively for push messages from server to consumers, in that case without acknowledging the receiving.

Having consumers register and unsubscribe via TCP shouldn't create to much overhead.

**Comment by NikolaiGit** [comment]
Ok i wasn't sure what our arrangement was
