### ISSUE TITLE
Downcast der Payloads

### ISSUE THREAD

**Issue by NikolaiGit** [TINF15ITNS/MB#13]
Ich glaube, wir haben hier noch nicht die optimale Lösung gefunden. 

Wir könnten zum Beispiel noch:
1. alle Downcasts mit instanceof überprüfen
2. alle Downcasts mit dem MessageType überprüfen
3. überlegen, ob man da was mit Generics machen kann

**Comment by naibaf0** [comment]
Kannst du mal bitte auf den Code verweisen um den es geht (welches file/methode). Dann werfe ich morgen einen kurzen Blick drauf.

**Comment by NikolaiGit** [comment]
Ähm in fast jeder Methode von Producer, Consumer und MessageServer wird aus dem Payload des Interface-Types, welches man aus ser Message bekommt, auf einen spezielleren Typ gecasted

**Comment by NikolaiGit** [comment]
Es geht mir hier grundsätzlich drum, wie das mit den Donwncasts im kompletten Code gehandelt werden soll. Im Moment haben wir überall solche Downcasts:
`PayloadMessage pm = (PayloadMessage) m.getPayload();`

Meine Frage war nun, ob es schöner/besser/schlauer wäre, diese Casts mit instanceof zu überprüfen.
Und danach zu überprüfen, ob der Payload-Typ zum MessageType passt.

**Comment by naibaf0** [comment]
Ja, es macht Sinn dies mit instanceof zu testen. theoretisch passiert da zwar nie ein Fehler, wenn wir es korrekt implementieren, aber immer lieber zu viel Errorhandling als zu wenig...

**Comment by NikolaiGit** [comment]
Getan!

**Comment by naibaf0** [comment]
Siehe #37. Hierbei gab es ein paar Fehler.

Das muss noch überprüft werden.

**Comment by naibaf0** [comment]
Durch mehrere Commits gefixt.
