### ISSUE TITLE
Confirmation process

### ISSUE THREAD

**Issue by NikolaiGit** [TINF15ITNS/MB#15]
Der MessageServer schreibt im Moment in die Antwortmessage: "ok" oder "not registered", falls der MS den Producer noch nicht kennt. 

Diese Variante ist aber eigentlich auch unschön. Man müsste auch so nen Enum dafür erstellen.

**Comment by NikolaiGit** [comment]
Für PayloadProducer gibt's die Success-Variable ... sowas? dabei, iwie ist das im Moment auch bissel unschön oder?

**Comment by naibaf0** [comment]
Ich halte das nicht für unschön. Das wäre definitiv nur etwas fürs Backlog.

Wir schicken die Nachricht hin, und wenn man sie genauso zurück erhälrt wie sie hinging, nur mit success = true, dann wissen wir das alles geklappt hat.

**Comment by naibaf0** [comment]
Nur ein enum würde das hier eher verschleiern. Bin mir nicht sicher ob das besser ist.

**Comment by NikolaiGit** [comment]
Dann würde ich dem PayloadMessage auch so eine Success-Variable hinzufügen, um anzuzeigen, dass der Server die Nachricht erhalten hat und weiterleiten wird.

Dann ist es synchron zu dem PayloadProducer

**Comment by oiooio** [comment]
Success ist jetzt komplett in den Payloads komplett implementiert, jetzt muss die Benutzung noch eingebaut werden.

**Comment by oiooio** [comment]
Consumer benutzt jetzt die variable komplett, jetzt muss diese vor immer vom Server gesetzt werden

**Comment by naibaf0** [comment]
Done.
