### ISSUE TITLE
Verwirrung durch Message und Message

### ISSUE THREAD

**Issue by NikolaiGit** [TINF15ITNS/MB#17]
Wir nennen die Objekte, die wir rumschicken Message, aber auch den MessageType und benutzen Message in Methodennamen und es ist vlt. auf den ersten Blick unklar, was wir jetzt meinen ...

Vorschlag: 
Wir passen auch die ganzen Konsolenausgaben in den CLI-Klassen so an, dass wir einem Thema folgen. Vorschlag war ja mal die Producer sind Online-Zeitungen, die Push-Nachrichen verfassen, und die Consumer sind normale Leutschens. Dann nennen wir den MessageType PushMessage und ein Methodenname ist zum Beispiel dann sendPushMessage() in Producer. 
(Dieses Problem ist jetzt nochmal stärker in Vorschein getreten durch meine Umbenennungen. Vorher hieß die angesprochene Methode sendBroadcastMessage(), was die Technik vorschreiben würde, die in der Methode benutzt wird (oder verstehe ich hier die Bedeutung des Wortes broadcast falsch???)).

**Comment by naibaf0** [comment]
Ein broadcast etwas, das Broad gecastet wird, also an ein breites Feld ausgestrahlt wird. Dies war eien Message die via UDP an einen Multicast geschickt wurde. Der Name war schon passend.

Bitte vermerke so Namensänderungen in Commits, ansonsten verstehen wir unseren eigenen Code nicht mehr, wenn Funktionen die Namen wechseln.

**Comment by naibaf0** [comment]
Und wir passen definitiv nicht die CLI Klassen an, damit er zu einem angehmeeren Namensmuster im Code passt. Der Code ist Mittel zum Zweck. Die CLIs sind das Frontend und das einzige wo Namen tatsächlich relevant sind.
Die Funktionsnamen sollten aussagekräftig sein, aber nicht übertreiben. Und außerdem kommt da noch überall Javadoc hin der ihn erklärt.

**Comment by naibaf0** [comment]
wir könnten zumindest den MessageType in Broadcast oder Post (also wie Blogpost nicht wie die Post :D) oder so umbenennen.

In der Hinsicht hast du recht das wir da im Namen unterscheiden sollten.

**Comment by NikolaiGit** [comment]
Ok ich wäre dafür, wenn wir alle in Post umbennen. 

Ich meinte aber eher, dass wir uns auf ein Thema festlegen. Auch in der Aufgabenstellung gibt er als Beispiel die Ergebnisse von Fußballspielen und ich hatte mal vorgeschlagen wir nehmen als Thema Push-Nachrichten von Online-Zeitungen. In ProducerCLI geben wir dann aus: "Wie soll ihre Online-Zeitung heißen?" anstatt ""Bitte geben Sie den gewünschten Namen für den Produzenten ein:"

Und wenn wir dieses Thema nehmen würde, dann hätten wir doch auch anstatt Post PushMessage oder PushNachricht nehmen können.
