### ISSUE TITLE
Aufbau der Producer-Klasse

### ISSUE THREAD

**Issue by NikolaiGit** [TINF15ITNS/MB#18]
Beim Testen ist mir folgendes aufgefallen: Er fragt erst den Namen des Producers ab, schreibt dann ne Message an der Server, ob dieser nicht schon belegt ist und das alles bevor er sich registriert hat!!! Sollte die Abfrage, ob der Name nicht schon existiert, nicht durch die RegistrierungsMessage erfolgen und dann diese Message serverseitig fehlschlagen lassen? 
So ist doch eigentlich eher unsere Struktur oder?

**Comment by naibaf0** [comment]
Dies hatte ich mir lange überlegt und es hat so am meisten Sinn gemacht. Ich muss mal kurz überlegen wieso.

**Comment by naibaf0** [comment]
Die Registrierungsmessage kann erst geschickt werden, wenn das Objekt Producer erstellt ist. Im Konstruktor sollte das nicht geschehen.

Ich sehe das das holprig ist, aber da immer nur eine CLI für einen Producer verantwortlich ist macht das durchaus noch Sinn.

--> Backlog.

**Comment by NikolaiGit** [comment]
Ok ich verstehe was du meinst und halte das auch für sinnvoll (-> Sebastian :) ). Diesen Punkt sollten wir nur in der Dokumentation auf jeden Fall ansprechen, dass die vorhandenen Producer, ohne vorherige Registrierung beim Server, abgefragt werden dürfen. Denn zum Beispiel wenn ein Producer eine Push-Nachricht absenden will, ist das anders. Hier überprüft sinnvollerweise der MS erst, ob der Producer schon registriert ist. Oder wir müssten das beim MS ändern?

**Comment by naibaf0** [comment]
Bei einer Push Nachricht ist es auf jeden Fall Sinnvoll, sicherzustellen, das der Producer existiertund registriert ist.
