### ISSUE TITLE
Exception-Handling

### ISSUE THREAD

**Issue by NikolaiGit** [TINF15ITNS/MB#19]
Ich hab einige Male kein korrektes Exception-Handling betrieben (habe immer nur den StackTrace ausgegeben).

Erinnerung an mich: Darf deser Fehler nicht auftreten, dann werfe ne RuntimeException. Ansonsten handle sie

**Comment by naibaf0** [comment]
Exception handling muss überall noch sauberer betrieben werden. Im Gegensatz zu den Interfaces ist das etwas, was unter Umständen entscheidend sein könnte.

**Comment by oiooio** [comment]
Weitere Bearbeitung in #22.
