### ISSUE TITLE
What kind of serialization should we use?

### ISSUE THREAD

**Issue by oiooio** [TINF15ITNS/MB#2]
Currently we use XML. Since the communication via UDP requires us to convert this string to a byte array we could directly serialize the message objects to a byte array.

(Taken from the readme)

**Comment by naibaf0** [comment]
I do not think that directly serializing to byte array gives us an advantage.

The only message sent via udp will be the ones from server to consumer. however when the producer first sends the message, the server has to read the message anyway to determine the message type (broadcast or deregistration).

For simplicities sake it might also make sense to not send the entire serialized message object to the consumer, but only a simplified one containing sender and message content, as the other message types are obsolete here?

**Comment by NikolaiGit** [comment]
I think there is an advantage: 
The XML-En/Decoder creates a new Instance with the newInstance()-method from Class and needs a nullary constructor. And it doesn't make sense to implement such a constructor in our Messageclass. So ...
