### ISSUE TITLE
Eingabe zu abonnierender Produzenten funktioniert nicht

### ISSUE THREAD

**Issue by NikolaiGit** [TINF15ITNS/MB#20]
Habe beim durchtesten bemerkt, dass die Zeile 60 in ConsumerCLI nicht funktioniert. Da kam ne ArrayOutOfBoundsException: 0 in dieser Zeile. @oiooio, du hattest die erstellt, schaust du mal bitte danach? Ich hatte einfach mal einen Producer mit Namen "Test" erstellt und wollte den dann abonnieren
Danke

**Comment by naibaf0** [comment]
Zeile 60 ist aber unsubscribe. Abbonieren ist ein paar Zeilen drüber. Der Code ist aber nahezu identisch. ;)

Ich habe nichts getestet, aber @oiooio fragt hier jeweils:

``` java
if (s[0] != null) { ... }
```

In der Zeile darüber werden s1 und s2 aber jeweils dynamisch erstellt, dementsprechend könnten sie auch die Länge 0 haben. In dem Fall gibt es s[0] nicht und es fliegt eine ArrayOutOfBounds Exception um die Ohren.

**Comment by oiooio** [comment]
Ich kann die Methode gerne testen, habe sie aber keineswegs in dieser fehlerhaften Form implementiert. Die aktuelle Fassung mit `if (s[0] != null) { ... }` stammt aus fogendem Commit von @NikolaiGit  https://github.com/TINF15ITNS/MB/commit/14a29a6bdd85c0b8aad59e818543b4db7e843fd7

**Comment by naibaf0** [comment]
@oiooio Nikolai ist im Urlaub ;)

Das ganze lässt sich aber glaube ich ganz einfach fixen, indem wir es zu `if (s.length() != 0)` oder etwas ähnliches ändern

**Comment by naibaf0** [comment]
Jup, ich mache das gerade. Das wirft aber erneut an der Stelle das Errorhandling auf.

Via CLI einfach mitteilen, das irgendetwas nicht geklappt hat ohne zu sagen wieso oder eine Lösung zu präsentieren scheint mir falsch

**Comment by oiooio** [comment]
Ok, habe das jetzt mal entsprechend angepasst. Die Variablen hießen auch s1 und s2, haben jetzt sprechendere Namen.

**Comment by NikolaiGit** [comment]
Ok habe beim Testen wieder einen Fehler festgestellt: 
Dies ist die Ausgabe:

Bitte wählen Sie durch Eingabe einer Zahl:
(1) Abmeldung vom Server
(2) Liste von Produzenten ansehen
(3) Abonnieren von Produzenten
(4) Produzentenabo kündigen
(5) Abonnements anzeigen
(6) erhaltene Nachrichten anzeigen
(7) Beenden der CLI
3
Welche Produzenten möchten Sie abonnieren?
(Bei mehreren bitte mit Komma trennen.)Focus Online
Es war nicht möglich, die folgenden Produzenten zu abonnieren:
- FocusOnline

Heißt doch, hier hat er das Leerzeichen in der Mitte fälschlicherweise rausgenommen und dadurch stimmt FocusOnline natürlich nicht mit Focus Online überein.
Weil ich mich mit diesem Replace Zeugs gar net auskennen, würde ich euch  bitten, dass nochmal zu überprüfen

**Comment by oiooio** [comment]
Wir hatten mal festgelegt, dass keine Produzenten mit Whitespaces existieren können. Hierauf basiert das Entfernen dieser. 

Da das anscheinend ja wenig praktikabel is gilt ab jetzt einfach folgende Konvention:
- Produzentennamen können keine Kommata enthalten
- Ansonsten sind alle Zeichen zulässig

@naibaf0 Erfordert das im Producer noch Änderungen?

**Comment by NikolaiGit** [comment]
Bei der Eingabe der Produzenten wird dies aber nicht abgelehnt und auch sonst nirgendwo verweigert. Ich probiers doch gerade mal
Ich splitte erst nach Kommas und laufe dann über das Array und trimme

**Comment by oiooio** [comment]
Eingabe im Consumer müsste jetzt korrekt funktionieren

**Comment by NikolaiGit** [comment]
`String[] toSubscribe = scanner.nextLine().split(",");
                    for (int i = 0; i < toSubscribe.length; i++) {
                        toSubscribe[i] = toSubscribe[i].trim();
                    }
                    String[] failedSubscriptions = user.subscribeToProducers(toSubscribe);`

Ich hätte es so gemacht. Hast du deins getestet? Wenns funktioniert können wir ruhig deinen Einzeiler nehmen.

**Comment by oiooio** [comment]
Laut meinem kurzen Testlauf funktioniert es, du kannst aber wenn du Zeit hast auch testen, das kann man nie genug machen :wink:

**Comment by naibaf0** [comment]
In Producer sind momentan noch Produzentennamen die ien Komma enthalten erlaubt. Ich kümmere mich gerade darum.

**Comment by NikolaiGit** [comment]
`String[] toSubscribe = scanner.nextLine().split(",");

	for (int i = 0; i < toSubscribe.length; i++) {

		toSubscribe[i] = toSubscribe[i].trim();

	}

String[] failedSubscriptions = user.subscribeToProducers(toSubscribe);`

Das müsste funktionieren. Hab das gestern parallel zum Sebastian erstellt und habe dann seins übernommen, weils nen Einzeiler war

**Comment by naibaf0** [comment]
Fix in  50720bff
