### ISSUE TITLE
Welche Aktionen des Consumers sollen unregistriert möglich sein?

### ISSUE THREAD

**Issue by oiooio** [TINF15ITNS/MB#21]
Hier https://github.com/TINF15ITNS/MB/commit/f3f67456c4dc665d63006e328fd68ab3207dae7c hab ich es erstmal so gelöst:
'1' Anmeldung: Ja
'2' Abmeldung: Nein
'3' Produzentenliste: Ja
'4' Abonnieren: Nein
'5' Deabonnieren: Nein
'6' Liste der Anmeldungen: Nein
'7' Beenden: Ja

Zusätzlich: Momentan wird in der CLI Klasse gespeichert, ob man registriert ist. Sollte das nicht eher in der Consumer Klasse selbst sein?

**Comment by naibaf0** [comment]
1. Klingt gut.
2. Ich habe im Producer vorhin einen Boolean eingefügt, der das im Objekt selbst speichert. Dazu eine isRegistered Methode.

Das könnte man im Consumer mirroren
