### ISSUE TITLE
Konsolenausgaben und Stacktraces außerhalb der CLI

### ISSUE THREAD

**Issue by oiooio** [TINF15ITNS/MB#22]
Konsolenausgaben und Stacktraces sollten nie und nimmer außerhalb der CLI erfolgen, das machts einfach unübersichtlich und die Trennung in Logik und CLI überflüssig.

**Comment by oiooio** [comment]
Beim Aufräumen auch Util nicht vergessen :grin:

**Comment by NikolaiGit** [comment]
Ich würde einfach mal drüber gehen und bei so catch-Blöcken, wie bei dem Verbinden der beiden Pipes ,ne RuntimeException im catch-Block werfen. Begründung: Diese Exception im angesprochenen Beispiel kann (eigentlich) nicht eintreten, weil sie geworfen wird, wenn der zu verheiratenden Pipe schon verheiratet ist. Sowas kann aber in der Consumer-Klasse gar nicht passieren. Deswegen ne RuntimeException, weil, wenn dies doch eintreten sollte, dann stellt die Situation eine nicht vom Program selbst behebare Situation dar und soll auch zum Programmabbruch führen

**Comment by naibaf0** [comment]
In dem Fall halte ich die Benutzung von RuntimeException für sinnvoll.

**Comment by NikolaiGit** [comment]
Hier sind mal die Stellen, wo ich jetzt nicht mal einfach ne RuntimeException werfen wöllte:
1. Consumer Zeile 269 letzte Anweisung in run-Methode:
   Vorschlag: Fehler schlucken und nichts machen. Bedeutet dann soviel wie, wenn ich nichts lesen kann, dann hat der Absender halt Pech gehabt. Aber auch hier dürfte dieser Fehler nicht auftreten(wir haben ja an dieser Stelle kein Timeout gesetzt oder sowas)
2. Util Zeile 36: Ich würde sagen, die Methode darf IOException weiter nach oben leiten. Dann muss sich der Aufrufer darum kümmern, wenn das DatagramPacket doch zu kurz sein sollte oder sowas. Und das wird dann ignoriert (siehe erster Punkt)
3. Util Zeile 62 + 64 genau das gleiche wie 2.
4.  MessageServer 59: Hier dürfte eigentlich auch nichts passieren, ich würde auch ne RuntimeException werfen
5. MessageServer 112: Hier ist diese Änderung vom Sebastian, damit die EOFException nicht sichtbar ist... nichts ändern? und beim Fangen der ClassCastException ne RuntimeException werfen?

Hier bitte nochmal eure Meinung zu abgeben. Möchte das nicht alleine entscheiden.

Wenn dies hier geklärt ist, dann ist überall ExceptionHandling betrieben worden.

**Comment by oiooio** [comment]
Nummer 1 habe entsprechend deines Vorschlages geändert, hört sich stimmig an.

**Comment by NikolaiGit** [comment]
Kümmerst du dich um den Rest?

**Comment by oiooio** [comment]
Vier und fünf habe ich umgesetzt, bei zwei und drei weis ich auch nicht weiter, zur not ne runtime exception werfen und dann is gut

**Comment by NikolaiGit** [comment]
wenn ich da nach oben weiterleite kommt es bei 1 an und wird verworfen oder?

**Comment by NikolaiGit** [comment]
Ok @naibaf0 : Ich ändere jetzt 2 und 3, wie ich meine. Wenn du zeit hast und es dir nicht gefällt, dann ändere es noch bitte

**Comment by naibaf0** [comment]
Sofern das nicht zu nem Bug führt bin ich damit vermutlich einverstanden ;)

**Comment by naibaf0** [comment]
Ist so übernommen.
