### ISSUE TITLE
Ausgabe der Broadcasts in der ConsumerCLI

### ISSUE THREAD

**Issue by oiooio** [TINF15ITNS/MB#23]
Die Eingabe von z.B. der Liste von welchen Produzenten man sich abmelden will sollte nicht durch Broadcasts unterbrochen werden können. Diese sollen erst nach der Eingabe der Liste ausgegeben werden.

**Comment by oiooio** [comment]
An dieser Stelle sind wohl Pipes Mittel der Wahl.

**Comment by naibaf0** [comment]
Mit #29 sollte es eigentlich nun klappen, tut es aber nicht...

**Comment by oiooio** [comment]
Also muss jetzt der Benutzer immer nach seinen neuen Nachrichten fragen? Lassen wir das so?

**Comment by NikolaiGit** [comment]
Theoretisch können wir das mit den Pipes auch wieder rausnehmen, da das mit den 2 Threads auf eine Konsole doch nur nicht geklappt hat, weil der Consumer überhaupt keine Nachrichten empfangen hat.

Aber wie willste das unterscheiden, das er erst nachschaut, ob du gerade was am eingeben bist?

**Comment by oiooio** [comment]
Also der Ansatz mit den Pipes ist absolut richtig, keine Frage. Letztendlich hatte ich mich nur gefragt, ob wir noch etwas an der Ausgaberoutine ändern wollen.

**Comment by naibaf0** [comment]
Ich bin nicht so ganz drinne in der Pipe Implementierung, aber was ich am coolsten fände:

```
Bitte wählen Sie durch Eingabe einer Zahl:
(1) Abmeldung vom Server
(2) Liste von Produzenten ansehen
(3) Abonnieren von Produzenten
(4) Produzentenabo kündigen
(5) Abonnements anzeigen
(6) Erhaltene Nachrichten anzeigen (5 neue)
(7) Beenden der CLI
Eingabe: 
```

Es wäre schön wenn man wie oben sehen könnte, dass es Nachrichten gibt. Falls die Anzahl nicht möglich ist könnte man zumindest anzeigen, dass neue da sind, falls der pipedwriter nicht leer ist.

**Comment by NikolaiGit** [comment]
Also mit 5 neue wäre über Umwege möglich. Man müsste jedes Mal, wenn der User die Option bekommt "Bitte wählen Sie durch Eingabe einer Zahl:" vorher alles aus der Pipe lesen und nach abgeschickten messages getrennt in einem String in ner List speichern und dann die Länge der List dran hängen

Nur das neue da sind geht sogar schwieriger, da nicht die CLI sondern der Consumer die Referenz auf den PipedReader hält. Man kann nämlich nicht einfach fragen pr.ready().

Variante 1 kann ich implementieren wenn gewünscht

**Comment by naibaf0** [comment]
@NikolaiGit Ließe sich eventuell einfach eine Variable `int messageCount = 0;` und eine Methode `public int getMessageCount()` implementieren, die wenn eine neue Message ankommt 1 hochgezählt wird und die resettet wird, wenn der Consumer die messages liest?

**Comment by NikolaiGit** [comment]
Klar das ginge ziemlich einfach, so einfach hab ich nicht gedacht :): Wird umgesetzt!

**Comment by NikolaiGit** [comment]
Naja das ist halt ein bisschen unschön: Die Kommuniktation zw den beiden Threads mache ich ja extra mit ner Pipe, damit ich nicht von dem einem Thread auf ner Variable des anderen rumfuhrwerke. Sonst könnte ich die neuen Nachrichten ja einfach in ne List<String> im Hauptthread packen. 
Und sowas würde ich ja hier machen, wenn ich von dem nebenläufigen Thread die Variable messageCount ausm Hauptthread hochzähle.

Wenn das nicht unschön sein sollte, dann kann ich das implementieren

**Comment by oiooio** [comment]
Es wird jetzt ausgegeben, ob neue Nachrichten vorhanden sind.

9754e7d1d2516218ab063d96f89c0383717c80aa
