### ISSUE TITLE
Readme aktualisieren

### ISSUE THREAD

**Issue by ramedlawH** [TINF15ITNS/MB#26]
Also ich schlage vor die Readme zu aktualisieren. Die Informationen dort sind nicht mehr aktuell.

Nur so werdet ihr :100: % erreichen.

**Comment by oiooio** [comment]
Diese Repo ist nicht bewertungsrelevant :stuck_out_tongue_winking_eye:

**Comment by naibaf0** [comment]
Klingt gut. :relieved:
