### ISSUE TITLE
Deregistrationsprozess Consumer

### ISSUE THREAD

**Issue by oiooio** [TINF15ITNS/MB#27]
Aus Consumer.java

```
public boolean deregisterFromServer() {
        Message answer;
        try {
            answer = Util.sendAndGetMessage(new Message(MessageType.DeregisterConsumer, new PayloadDeregisterConsumer(consumerID)), serverAddress, serverPort);
        } catch (IOException e) {
            return false;
        }

        PayloadDeregisterConsumer answerPayload = (PayloadDeregisterConsumer) answer.getPayload();
        if(!answerPayload.getSuccess()) return false;

        try {
            udpSocket.leaveGroup(mcastadr);
        } catch (IOException e) {
            //TODO return true/false?
        }
        registered = !answerPayload.getSuccess();
        return answerPayload.getSuccess();
    }
```

Es kann passieren, dass wenn `Util.sendAndGetMessage(new Message(MessageType.DeregisterConsumer, new PayloadDeregisterConsumer(consumerID)), serverAddress, serverPort);` erflogreich war, der Consumer für den Server abgemeldet ist, danach jedoch `udpSocket.leaveGroup(mcastadr);` fehlschlägt, der Consumer also folglich noch in der MCGruppe drin ist. Wie gehen wir damit um?

**Comment by naibaf0** [comment]
Wann schlägt udpSocket.leaveGroup denn fehl? Wenn der Server offline ist? 
oder auch aus anderen Gründen? 
Wenn er offline ist, ist ja eh alles vergessen und er damit aus der Gruppe raus, oder?

Ansonsten könnte man beide  Methoden in einem try-catch abhandeln, wenn wir bei dem Fehler eh nicht mehr unterscheiden. Oder im try-catch auch ein return false einführen.

**Comment by naibaf0** [comment]
Das Problem ist natürlich trotzdem noch da, dass der Server ihn dann nicht mehr kennt, er aber noch auf dem udpSocket registriert ist.

Ich bin mir nicht sicher, wie man das am besten behandelt.

**Comment by oiooio** [comment]
Es wird jetzt false zurückgegeben.
