### ISSUE TITLE
Datagram Packets von MessageServer -> Consumer

### ISSUE THREAD

**Issue by naibaf0** [TINF15ITNS/MB#29]
Ich habe an dieser Stelle jetzt noch ein bisschen getestet, hier sind meine Funde:

Es funktioniert aktuell noch nicht. Im MessageServer wird alles konform verarbeitet und losgeschickt, es kommt aber eben nicht beim Consumer an.
- Eventuell liegt es an den zwei Klassen in der Util, insbesondere der getMessageOutOfDatagramPacket.  @NikolaiGit Kannst du erklären, was da passiert? Mir ist das nämlich nicht so klar. Beim schnellen Googeln diesbezüglich gab es keine Implementierungen, die mit Inputstreams etc. herummachten...
- Eine der Regeln von udps.receive (genutzt in WaitForMessage.run im consumer Paket) ist, dp midestens so groß sein muss wie das zu erwartende Paket, ansonsten wird es beschnitten. Ich habe mir die Größen mal ausgeben lassen, und das dp Blanko Paket war 279 und das zu sendende 285. Hier könnte auch ein Hund begraben liegen...

**Comment by naibaf0** [comment]
Wenn sich die hier nicht in akzeptabel wenig Zeit fixen lässt bitte eine Alternative mit TCP und mehr Logik im Server implementieren. Dies sollte einfacher gehen und wir haben noch genug andere Baustellen. ;)

**Comment by NikolaiGit** [comment]
super, danke fürs genaue Testen! Ich kümmere mich drum. Ich kann mir gut vorstellen, dass hier der Fehler liegt. Wenn wir einfach ein int verschicken wollen, dann können wir schon vorher die Länge angeben, egal was in dem int für ein Wert gespeichert ist. In unserem Fall geht das nicht, da man ja nicht weiß, was hinter Payload steckt. Dafür gabs im Skript ne Vorgehensweise (Java 3E Folie 183), die ich versucht habe zu implementieren.

Mal schauen

**Comment by NikolaiGit** [comment]
Ok die Situation ist folgende: 

`try (MulticastSocket udpSocket = new MulticastSocket(serverPort);) {
            multicastadr = InetAddress.getByName("225.225.225.225");
            InetAddress serverAddress = InetAddress.getByName("localhost");

```
        udpSocket.setTimeToLive(1);

        Message m = new Message(MessageType.Broadcast, new PayloadBroadcast("Test", "Hallo!!!"));
        // schauen, ob der Absender sich beim Server auch angemeldet hat
        DatagramPacket dp = Util.getMessageAsDatagrammPacket(m, multicastadr, serverPort);


        System.out.println("Sende jetzt die Nachricht");
        udpSocket.send(dp);
        System.out.println("Abgeschickt");


        System.out.println("\nTesten wir das umwandeln mal\n");
        Message a = Util.getMessageOutOfDatagramPacket(dp);
        PayloadBroadcast pb = (PayloadBroadcast) a.getPayload();
        System.out.println(pb.getSender() + " meldet: " + pb.getMessage());

    } catch (Exception e) {`
```

Das umwandeln eines Message-Objektes in ein DatagramPacket funktioniert (=erster Absatz)
Sodann wird im MessageServer das Packet weggeschickt. 
Wenn ich noch in der MessageServer-Klasse wieder aus dem DatagramPacket ein Message-Objekt mache, klappt das mit dem bisher implementierten auch! (siehe Abschnitt 3)

Das Problem entsteht hier: 
`DatagramPacket dp = Util.getMessageAsDatagrammPacket(MessageFactory.createBroadcastMessage("", ""), serverAddress, serverPort);
            try {
                System.out.println("Warte jetzt auf Nachricht: ");
                udps.receive(dp);
                System.out.println("Hab ne UDP Nachricht erhalten und wandele sie jetzt in ne Message um");
                Message m = Util.getMessageOutOfDatagramPacket(dp);`

Und zwar ist das DatagramPacket hier nach dem erhalten der Nachricht nicht ein äquivalentes zu dem nach dem Senden in der MS-Klasse. Das mit dem leeren DatagramPacket-Erstellen klappt nicht. 

Soweit bin ich im Moment gekommen. Ich schau jetzt mal weiter, woran es da liegt.

**Comment by NikolaiGit** [comment]
erstelle ich das Blanke-Objekt so: 
`DatagramPacket dp = Util.getMessageAsDatagrammPacket(MessageFactory.createBroadcastMessage("kajsdkjasdhkasd", ""), serverAddress, serverPort);`
Dann ist die Größe 292
Das klappt an anderer Stelle iwie nicht.

Halt Stop, daran liegts doch! Mit 292 klappts!

**Comment by NikolaiGit** [comment]
Er hat schön in seinem Skript ausgelassen, wie man damit umgeht, wenn die Länge des zu erhaltenden Packets erst zur Laufzeit feststeht. Er hats immer nur mit festen Länge dargestellt. 

Das ist nen Problem und ich versuche noch ne Lösung zu finden. 
Was aber sowieso nen Problem werden könnte: Wir können ja kein Blanko-Objekt erstellen, dass sowohl ne Message mit PayloadProducer und ne Message mit PayloadBroadcast reinpasst...

**Comment by naibaf0** [comment]
`byte[] buffer = new byte[65508];`

Das ist die Maximale Größe die ein UDP Packet haben kann.

Gäbe es Nachteile wenn man immer dies als Blanko verwendet.

Quelle siehe hier: http://tutorials.jenkov.com/java-networking/udp-datagram-sockets.html

**Comment by NikolaiGit** [comment]
Habs mal kurz in meiner Testumgebung implementiert. Da hat es geklappt. Ausführlicher testen tu ich ab 6, dann bin ich vom Fußball wieder da.

**Comment by naibaf0** [comment]
Kannst du das vorher noch implementieren? Damit @oiooio da mit weiterarbeiten kann?

**Comment by naibaf0** [comment]
Dann könnte ich das auch gerade noch testen und ein bisschen besser voran kommen.

**Comment by naibaf0** [comment]
Ich habe es nun ausprobiert, leider wurde noch nichts ausgegeben. Ich hate aber keine Zeit mehr das zu Debuggen und zu sehen, ob das Problem beim Pipen oder dem senden via udp liegt.

**Comment by NikolaiGit** [comment]
Pipe noch nicht getestet, aber jetzt erhält der Consumer Nachrichten!!!! Ich musste die MulticastSockets in der MS- und Consumer-Klasse an einen bestimmten Port binden (hab den selben wie TCP genommen, das geht)

**Comment by NikolaiGit** [comment]
Die Variante mit der maximalen Größe des DatagramPackets scheint wohl echt die einzig gangbar zu sein. Ich habe vorhin nochmal einige Zeit darüber nachgedacht, aber mir ist keine Alternative eingefallen. Werde vlt nochmal das Internet befragen, aber das Issus sollte damit geklärt sein
