### ISSUE TITLE
How to send the payload?

### ISSUE THREAD

**Issue by NikolaiGit** [TINF15ITNS/MB#3]
# Änderungsvorschlag:

Die Klasse Message hält anstatt eines Strings payload ein Objekt vom Typ eines Interfaces payload. Da wird dann im Konstruktor ein Objekt reingesteckt, was von dem Interface erbt. Die implementierende Klasse hat dann die benötigten Attribute und das Interface ist nur so als Marker-Interface gedacht.
Das ist, denke ich, bedeutend schöner, als wenn man in ner API definiert, wie mit dem Payload des Messagetypes umzugehen ist!!!

**Comment by NikolaiGit** [comment]
Ok, ich machs einfach mal. Alles alte, was in diesem Zusammenhang geändert wird, kommentiere ich mal aus, falls es euch doch besser gefallen sollte.

**Comment by naibaf0** [comment]
Ich verstehe nicht ganz was du meinst. 
Hilft vielleicht wenn du es implementierst.

_Du brauchst aber nicht auskommentieren sondern kannst löschen. Dafür ist GIT ja da, dass wir verschiedene Versionen der Files haben können. Mach ienfach speziell dafür einen Commit. Wenn er stört machen wir ihn rückgängig._

**Comment by NikolaiGit** [comment]
Also ich habs mal implementiert. Die Idee ist doch nicht so super wie gedacht, aber ich denke eleganter als vorher.

Nochmal zur Erklärung: 
Bisher wurde der payload als String verschickt. Kam also als Antwort vom MS alle verfügbaren Producer, so entstand nen ewig langer String mit ";"-getrennten Namen der Producer. Dann musste man auf der anderen Seite den String spliten, etc. Und für jeden Message-Typ gabs ne andere Vorgehensweise.

NUN: Erzeugt man ein Message-Objekt, dannübergibt man dem Konstruktor ein Objekt einer Klasse die das Marker-Interface Payload implementiert. Das Objekt hält nun die Informationen und man kann sie mit getter-Methoden abgreifen. Immer noch nicht ganz so schön, da man den payload erstmal downcasten muss (siehe Code). Da müssen wir uns was überlegen ...

**Comment by NikolaiGit** [comment]
Warte hab mir was überlegt: Ginge das nicht mit komplexen Enums?
