### ISSUE TITLE
Zustand der CLIs und zugehöriger Objekte muss wechseln wenn IOException kommt

### ISSUE THREAD

**Issue by naibaf0** [TINF15ITNS/MB#30]
In dem Fall ist der Server Offline, und dementsprechend sind alle Daten gelöscht.

Wenn der Producer also registriert ist und eine IO Exception erhält, so muss diese isRegistered nun false zurückgeben.

**Comment by oiooio** [comment]
Es dürfte jetzt überall wo eine IOException fliegt registered auf false gesetzt werden.
