### ISSUE TITLE
Ausgabe der Messages: Sieht man den Absender?

### ISSUE THREAD

**Issue by naibaf0** [TINF15ITNS/MB#31]
Das halte ich für sehr sinnvoll (sofern es mal funktioniert). Ich habe nicht nachgeschaut ob das da schon drinnen ist.

Falls nicht sollte es.

**Comment by naibaf0** [comment]
Ausgabe: 

```
Ihre neuen Nachrichten:

ersterSender
foobar

zweiterSender
foobaz

ersterSender
fuhbaz


```

**Comment by NikolaiGit** [comment]
Klar
In die Pipe wird reingeschrieben: 
`pw.write(payload.getSender() + " meldet: \n" + payload.getMessage());`
Der MessageServer leitet ja praktisch die selbe Nachricht weiter, die vom Producer kommt und da steht der Absendername und der Text drinne

**Comment by oiooio** [comment]
Sieht so aus:

```
Sie haben eine neue Push-Mitteilung:[Absender] meldet: 
[Nachricht]
```

(Ich ändere die Formatierung noch ein bisschen)
