### ISSUE TITLE
Sprechendere Ausgaben in MessagesServerCLI

### ISSUE THREAD

**Issue by oiooio** [TINF15ITNS/MB#33]
```
Verbindung aufgebaut
Antworte nun
Verbindung aufgebaut
Antworte nun
Verbindung aufgebaut
```

halte ich für wenig sinnvoll.  Hier vielleicht etwas mehr an Informationen für den Benutzer?

**Comment by oiooio** [comment]
Ist

```
private Message getProducerList(Message m) {
    System.out.println("Sende Produzentenliste an " + s.getRemoteSocketAddress().toString());
    return MessageFactory.createProducerListMsg(dataProducer, true);
}
```

so richtig? Oder gibt es eine Möglichkeit hier den Consumer eindeutiger zu identifizieren?

**Comment by NikolaiGit** [comment]
Ich hatte das nur zum Testen eingebaut, damit ich nicht debuggen muss, um zu sehen, was der MS gerade macht. 
Von mir aus gerne komplett weg!

**Comment by oiooio** [comment]
Eigentlich das gegenteil. Am besten im Server so viel wie möglich, denn man will ja sehen, was der so treibt. Die Frage war nur, wie ich die Konsumenten/Produzenten am besten im Server identifizieren kann (Port ändert sich ja ständig, also kann man damit niemanden eindeutig identifizieren)

**Comment by NikolaiGit** [comment]
Iwie ist meine Antwort hier verlorenen gegangen: 

Die Producer registrieren sich ja mit nem einzigartigem Namen und die Consumer bekommen ne Id. Also würde ich die Ausgaben in etwa so gestalten: 
"Der Consumer mit der ID 5 hat sich gerade abgemeldet" oder "Der Produzent Focus Online hat gerade eine neue Push-Nachricht verfasst"

**Comment by naibaf0** [comment]
Klingt gut. Ich würde es allerdings in Stichpunkten lassen. Das soll gewissermaßen eine Log Funkion sein, nicht ein Roman. also:

```
Consumer 5: abgemeldet
Produzent Focus Online: Neuer Broadcast
```

**Comment by naibaf0** [comment]
Oder umgekehrt:

```
Abgemeldet: Consumer 5
Neuer Broadcast: Focus Online 
```

**Comment by NikolaiGit** [comment]
getan mit eca85ce812e61201e2931b9fc315a5ae02fde464
