### ISSUE TITLE
UML-Diagramme erzeugen

### ISSUE THREAD

**Issue by NikolaiGit** [TINF15ITNS/MB#34]

**Comment by naibaf0** [comment]
Lassen sich diese denn in pngs oder jpgs oder ähnliches exportieren? @NikolaiGit 

Ich habe das Plugin nicht installiert und würde ungern jetzt noch Zeit darauf verwenden. ;)

**Comment by naibaf0** [comment]
Binde sie vielleicht schonmal in das Google Doc ein.

Aber nicht vergessen ,dass sie nochmal geupdatet werden müssen, wenn wir #36 abgearbeitet haben

**Comment by NikolaiGit** [comment]
Das geht mit einem Klick ganz einfach, habs gerade probiert. Man muss alles in Eclipse markieren und Ctrl+C und dann steckt er es in Word in iein Bildformat

**Comment by oiooio** [comment]
Mit der Standalone Version von Umlet kann man direkt in ein Format der Wahl exportieren.
