### ISSUE TITLE
Dokumentation schreiben

### ISSUE THREAD

**Issue by NikolaiGit** [TINF15ITNS/MB#35]

**Comment by naibaf0** [comment]
Es sollte noch jeder seine Matrikelnummer irgendwo eintragen.

**Comment by oiooio** [comment]
https://docs.google.com/document/d/12VWgNTNrxxbUs-V39UBOLWt4FAHKAh_1yEEbJQP3UbY/edit?usp=sharing

**Comment by oiooio** [comment]
Bitte hierbei #38 beachten.

**Comment by naibaf0** [comment]
Wurde beachtet. Ich habe die Formulierungen nochmals überarbeitet, aber inhaltlich und strukturell nichts verändert.
