### ISSUE TITLE
Interface Payload -> abstraktere Klasse Payload?

### ISSUE THREAD

**Issue by NikolaiGit** [TINF15ITNS/MB#36]
Eigentlich ändern würde sich ja nichts, wenn wir aus dem Interface eine abstrakte Klasse machen würden. Nur wir könnten sogar noch das Vorhandensein der Success-Variable vorschreiben.

**Comment by naibaf0** [comment]
Macht für mich Sinn. 
Ist auch von der Logik her besser.

**Comment by NikolaiGit** [comment]
Und eine weitere Sache: Sollten wir den Konstruktor von message nicht auf protected setzen, sodass man die MessageFactory nutzen muss?

**Comment by naibaf0** [comment]
Macht ebenfalls Sinn.

**Comment by oiooio** [comment]
Das vorhandensein der success Variable ist Implementierungssache. Eigentlich sind get/setSuccess ausreichend, ich bin eher für das Beibehalten des Interfaces.

**Comment by naibaf0** [comment]
@NikolaiGit : Ich sehe Sebstians Punkt. Die Variable ist eigentlich Implementierungssache, man könnte in einer anderen Implementierung den Success auch auf andere Weise Berechnen. Belassen wir es beim Interface.
@oiooio : Du hast gerade noch von setSuccess gesprochen. Diese Methode habe ich aus dem Interface und alle Klassen die sie implementierten herausgelöscht, da sie nie verwendet wurde (setSuccess erfolgt durch die MessageFactory)

**Comment by naibaf0** [comment]
ich habe mit 0d54cef a8a22b1 rückgängig gemacht.
