### ISSUE TITLE
Produzentenliste wird im Server bei irregulärem Beenden vom Producer nicht aufgeräumt

### ISSUE THREAD

**Issue by oiooio** [TINF15ITNS/MB#38]
Wenn man einen Producer "einfach" beendet, d.h. der Produzent keine Abmeldungsnachricht an den Server schickt taucht dessen Name immer noch in der Produzentenliste auf. Dies hat zur Folge, dass wenn ein Consumer die Produzentenliste anfordert auch alle Namen der Produzenten auftauchen, die irregulär beendet wurden. Auf diese kann sich der Consumer aber nicht einschreiben, und es kann auch kein neuer Produzent mit diesem Namen angelegt werden, obwohl er eigentlich frei ist.

**Comment by oiooio** [comment]
Wie es aussieht könnte man noch eine Hook für das Beenden über Strg+C einbauen, das Beenden über den CloseButton des Konsolenfesters (Windows) kann nicht ohne Weiteres gehandelt werden. **Somit muss dies unbedingt ind die Dokumentation.**

**Comment by naibaf0** [comment]
Ist drin.
