### ISSUE TITLE
Abgabe

### ISSUE THREAD

**Issue by oiooio** [TINF15ITNS/MB#39]
Was genau inkludieren wir jetzt?
- Dokumentation mit den Klassendiagrammen als PDF
- Javadoc
- die .jar Dateien (Producer, Consumer, MServer)
- Sourcecode

So richtig?

Edit: Keine Binaries nur die jars

**Comment by naibaf0** [comment]
Ich weiß nicht ob die Binaries sein müssen. Der hat die Jars zum ausführen und src, um anzusehen was er gemacht hat...

**Comment by naibaf0** [comment]
Enthalten sind:
- Dokumentation (mit UML) als PDF
- Ordner mit generiertem Javadoc
- Ordner mit Quellcode
- Ordner mit den 3 geforderten Jars

Alles in eine .zip Datei gepackt und losgeschickt.
