### ISSUE TITLE
util class?

### ISSUE THREAD

**Issue by naibaf0** [TINF15ITNS/MB#5]
The methods testConnection as well as getProducers are needed in both classes (Producer and Consumer) it might be worth it to move those methods into an utility class.

**Comment by naibaf0** [comment]
Oh, and 'sendAndGetMessage' as well.

**Comment by NikolaiGit** [comment]
This is a good point! I tried something like this in the class Message. There's a static method which converts a Message-object to a Datagrampacket ... Probably a new class in the message-packet?

**Comment by naibaf0** [comment]
yes

**Comment by naibaf0** [comment]
This is being implemented #11
