### ISSUE TITLE
Entering a message in the producerCLI

### ISSUE THREAD

**Issue by naibaf0** [TINF15ITNS/MB#8]
How do we want to handle this?
Is a message allowed to be multiple lines long?
Because if yes I have a problem utilizing only one Scanner Item, as it only scans lines and would end up in a neverending loop waiting for input.
One way would be to ask for the number of lines a message has before waiting for it. Then I can scan with nextLine() inside a for loop.
However that's not really cool. Anybody got better ideas?

**Comment by NikolaiGit** [comment]
Ähm probably i don't understand the problem but: nextLine() reads every char till there is a line break (something like \n in a String). If you're write and wirte a message in the commandline and it's to long for this line and goes further in the next, there is no really line break. Not a line break that nextLine() interprets this to stop.
(Englisch ist scheiße... versteht man was ich sagen will? :( )

Try the following code:

```
class Test {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        String s = sc.nextLine();
        System.out.println(s);
    }
}
```

And enter a  long text ...

**Comment by naibaf0** [comment]
Yes, you missed my point.
What I meant was that it would be great if messages sent could contain Linebreaks. Otherwise they will be unreadable if longer than one or two sentences.
However in that case the coding isn't as simple as what you wrote.

**Comment by NikolaiGit** [comment]
Ok this works:

```
class Test {
    public static void main(String[] args) throws IOException {
        StringBuffer s = new StringBuffer();
        Scanner scanner = new Scanner(System.in);
            while (scanner.hasNext()) {
            String sss = scanner.nextLine();
            if (sss.equals("end"))
                break;
            s.append(sss);
            s.append(new String("\n"));

        }
        System.out.println(s);
        scanner.close();
        }
}
```

But we have to tell the User that he has to end his message with the String "end" in a new Line

**Comment by naibaf0** [comment]
That is better than my variant.

**Comment by naibaf0** [comment]
Okay, das ist aber auch Mist. Jetzt ist man immer gezwungen, das ende zu markieren. Selbst bei einem Einzeiler.

Man kann glaube ich auch nicht mit hasNext die nächsten Zeilen überprüfen, dann wartet der endlos.

Ich überlege da nochmal ob das besser geht. Evtl dann doch nur eine zeile oder die Zeilenzahl vorher angeben...

**Comment by naibaf0** [comment]
I removed the Option. If wanted we can integrate it later
